config/routes.rb
Tomato::Application.routes.draw do
  
  devise_for :users
  get "user/feedbacks"

  namespace :admin do
    resources :restaurants do
      resources :reviews do
        resources :notes ,only: [:destroy]
        collection do
          get 'zomato'
          get 'burrp'
          get 'yelp'
          get 'foursquare'
        end
      end
    end
  end


  namespace :consumer do
    resources :restaurants, only: [] do
      member do
        get :overview
        post :overview
        get :restaurant
        get :features
        get :service
        get :dishes
        get :dish_chart
      end
    end
  end

  resources :restaurants do 
    resources :reviews do 
      member do
        get 'give_feedback'
      end
      collection do
        get 'zomato'
        get 'burrp'
        get 'yelp'
        get 'foursquare'
      end
    end
  end

  resources :feedbacks do
    resources :notes ,only: [:create,:destroy]
    resource :parameter, :only => :update
  end

  root :to => 'home#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :item, :rating, :why

  belongs_to :feedback

  before_save :normalize_item!

  def review
    feedback.review
  end

  def normalize_item!
    self.item = normalized_item
  end

  def normalized_item
    item.split(" ").collect(&:downcase).collect(&:capitalize).join(' ')
  end
end

app/controllers/admin/notes_controller.rb
class Admin::NotesController < ApplicationController
  before_filter :set_admin
  before_filter :authenticate_user!

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    redirect_to request.referrer
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!

  def update
    @note = Note.find(params[:id])
    if @note.update_attributes(params[:note])
      redirect_to restaurant_review_path(params[:restaurant_id],params[:review_id]), notice: 'Note was successfully Updated !'
    else
      render action: 'edit'
    end
  end

  def create
    @feedback = current_user.feedbacks.find(params[:feedback_id])
    @note = @feedback.notes.build(params[:note])
    if @note.save
      render :partial => 'notes/list', :locals => {:notes => @feedback.notes, :restaurant => @restaurant}
    else
      render notice: 'Unsuccessful !'
    end
  end

  def destroy
    @feedback = current_user.feedbacks.find(params[:feedback_id])
    @note = @feedback.notes.find(params[:id])
    @note.destroy

    redirect_to request.referrer
  end
end

app/helpers/admin/notes_helper.rb
module Admin::NotesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
/= button_tag 'Add a Note', class: "tiny button radius add-note"
#new_note_form
  .new-note-form
    = form_for [@feedback,Note.new], html: { class: 'note-form' } do |f|
      .field
        = f.label :item
        = f.text_field :item
      .field
        - [1,2,3,4,5].each do |rating|
          = f.radio_button :rating,rating
          = f.label rating
      .field
        = f.label 'Why ?'
        = f.text_field :why
      .field
        = f.submit 'Save Note' , class: 'btn btn-success save-button'
        = button_tag 'Cancel', class: "btn btn-danger cancel-button"

app/views/notes/_list.html.haml
#notes_list
  - if notes.present?
    %table.table-striped.small.table-bordered
      %tr
        %th.item Item
        %th.rating Rating
        %th.why Why ?
        %th.delete
      - notes.each do |note|
        %tr
          %td
            = note.item
          %td
            = note.rating
          %td
            = note.why
          %td
            = link_to 'X', (@admin ? admin_restaurant_review_note_path(restaurant,note.review,note) : feedback_note_path(note.feedback ,note)), data: { confirm: 'Are you sure?' }, method: :delete, class: 'delete-note'