config/routes.rb
Tomato::Application.routes.draw do
  
  devise_for :users
  get "user/feedbacks"

  namespace :admin do
    resources :restaurants do
      resources :reviews do
        resources :notes ,only: [:destroy]
        collection do
          get 'zomato'
          get 'burrp'
          get 'yelp'
          get 'foursquare'
        end
      end
    end
  end


  namespace :consumer do
    resources :restaurants, only: [] do
      member do
        get :overview
        post :overview
        get :restaurant
        get :features
        get :service
        get :dishes
        get :dish_chart
      end
    end
  end

  resources :restaurants do 
    resources :reviews do 
      member do
        get 'give_feedback'
      end
      collection do
        get 'zomato'
        get 'burrp'
        get 'yelp'
        get 'foursquare'
      end
    end
  end

  resources :feedbacks do
    resources :notes ,only: [:create,:destroy]
    resource :parameter, :only => :update
  end

  root :to => 'home#index'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :address, :name, :phone, :zomato_url, :burrp_url, :yelp_url, :foursquare_url
  has_many :reviews, :order => "id DESC"

  def collected_notes
    @collected_notes ||= reviews.collect(&:consolidated_notes)
  end

  def uniq_items
    collected_notes.collect(&:keys).flatten
  end

  def uniq_items_dist
    uniq_items.inject(Hash.new(0)) { |total, e| total[e] += 1 ;total}
  end

  def date_ordered_reviews
    reviews.order("review_created_at").group_by {|r| r.review_created_at.to_date}.to_a
  end

=begin
  def clusters
    @clusters ||= Util.cluster uniq_items_dist.keys
  end

  def cluster_label cluster
    label = cluster.first
    label_score = uniq_items_dist[label]
    cluster.each do |string|
      if uniq_items_dist[string] > label_score
        label = string 
        label_score = uniq_items_dist[string]
      end
    end
    label
  end

  def cluster_metrics cluster
    cluster_metrics = []

    date_ordered_reviews.each do |date ,reviews|
      puts date

      total_score = 0
      total_mentions = 0

      reviews.each do |review|
        notes = review.consolidated_notes
        cluster.each do |item|
          if notes[item]
            total_score += notes[item]
            total_mentions += 1
          end
        end
      end

      cluster_metrics << [date, {:total_score => total_score, :total_mentions => total_mentions}]

    end
    
    cluster_metrics.select {|e| e.second[:total_mentions] > 0}.map {|e| [e.first.to_time.to_i*1000, e.second[:total_score]/e.second[:total_mentions]] }
  end
=end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_filter :set_admin
  before_filter :authenticate_user!
  before_filter :authenticate_admin!
  before_filter :init_breadcrumb

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
    @review = Review.new
    render 'restaurants/index'
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    add_breadcrumb @restaurant.name,admin_restaurant_path(@restaurant)
    @reviews = @restaurant.reviews
    @review = Review.new(restaurant_id: @restaurant.id)
    #compute_cluster_metrics

    render 'restaurants/show'
  end

  def new
    @restaurant = Restaurant.new
    add_breadcrumb 'New Restaurant',new_admin_restaurant_path

    render 'restaurants/new'
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    add_breadcrumb @restaurant.name,admin_restaurant_path(@restaurant)
    add_breadcrumb 'Edit Restaurant',edit_admin_restaurant_path(@restaurant)
    render 'restaurants/edit'
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    if @restaurant.save
      redirect_to admin_restaurant_path(@restaurant), notice: 'Restaurant was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params[:restaurant])
      redirect_to request.referer, notice: 'Restaurant was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to request.referer, notice: 'Deleted a Restaurant successfully.'
  end

  private
    def authenticate_admin!
      redirect_to root_path, alert: "Admin area restricted !"  unless admin?
    end

    def admin?
      current_user.has_role? :admin
    end

    def init_breadcrumb
      add_breadcrumb 'Admin', admin_restaurants_path
      add_breadcrumb 'All Restaurants', admin_restaurants_path
    end

    def compute_cluster_metrics
      @clusters = @restaurant.clusters
    end

end

app/controllers/consumer/restaurants_controller.rb
class Consumer::RestaurantsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_restaurant
  before_filter :load_reviews
  before_filter :load_dish, only: [:dish_chart]

  layout 'consumer'

  def overview
    review_hash=@reviews.group("date(review_created_at)").count()
    @count_array = review_hash.to_a
    @count_array.sort! { |a, b| a.first <=> b.first }.collect! { |e| [e.first.to_time.to_i, e.second] }
    ob = Tools::ReviewsScore.new(@reviews)
    @trending_dishes = ob.trending_dishes
  end

  def category_chart

  end

  def restaurant
    ob = Tools::ReviewsScore.new(@reviews)
    @category = 'restaurant'
  end

  def features
    ob = Tools::ReviewsScore.new(@reviews)
    category = cookies['category']
    category_rating_hash = ob.category_rating_hashes([category])
    feature_rating_hashes_orig = ob.feature_rating_hashes(chart_parameters) if chart_parameters
    feature_rating_hashes_orig ? (rating_hashes_orig = category_rating_hash.merge feature_rating_hashes_orig) : rating_hashes_orig = category_rating_hash
    #Get date points from all features for use as keys
    keys = []
    rating_hashes_orig.values.each{|hash| keys.push hash.keys  }        #.inject {|union,hash| hash.keys | union.keys}
    keys.flatten!().uniq!
    if keys
      @rating_hash = {}
      (keys).each {|key,value| @rating_hash[key]=  rating_hashes_orig.values.collect{|hash| hash[key] } }
      #(keys).each {|key| @feature_rating_hash[key]= @parking_rating_hash[key],@ambience_rating_hash[key]}
      @rating = @rating_hash.to_a.collect{|r|  r[1].unshift(r[0].to_time.to_i)}
      @rating.sort! { |a, b| a.first <=> b.first }
      render json: {'columns'=>chart_parameters.push(category).collect(&:humanize),'rows'=> @rating}
    end
  end

  def service
    ob = Tools::ReviewsScore.new(@reviews)
    @category = 'service'
    render 'restaurant'
  end



  def dishes
    ob = Tools::ReviewsScore.new(@reviews)
    @dishes = ob.all_dishes
    cookies['dish']='South'
  end

  #Endpoint for returning chart data for a specific dish
  def dish_chart
    ob = Tools::ReviewsScore.new(@reviews)
    rating_hash = ob.time_vs_dish_rating @dish
    @rating = rating_hash.to_a.collect{|r|  [r[0].to_time.to_i,r[1]]}
    render json: {'columns'=>[@dish],'rows'=>@rating}
  end



  private
  def load_reviews
    load_restaurant
    load_start_and_end_dates

    @reviews = @restaurant.reviews.where(:review_created_at => (@start_date..@end_date))
    @reviews_score = Tools::ReviewsScore.new(@reviews)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def load_start_and_end_dates
    # Cookies were set on the browser.
    if (cookies['start_day'].present?)
      @start_date = Date.new cookies['start_year'].to_i, cookies['start_month'].to_i, cookies['start_day'].to_i
      @end_date = Date.new cookies['end_year'].to_i, cookies['end_month'].to_i, cookies['end_day'].to_i
    else
      @start_date = Date.today - 1000.days
      @end_date = Date.today
    end
  end

  def chart_parameters
  #TODO Memoize this shit
    if cookies['chart_parameters']
      @chart_parameters = cookies['chart_parameters'].split(',')
    else
      []
    end
  end

  def load_dish
    @dish = cookies['dish']
  end



end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :init_breadcrumb

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
    @review = Review.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    add_breadcrumb @restaurant.name,restaurant_path(@restaurant)
    @reviews = @restaurant.reviews
    @review = Review.new(restaurant_id: @restaurant.id)
  end

  def new
    @restaurant = Restaurant.new
    add_breadcrumb 'New Restaurant',new_restaurant_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    add_breadcrumb @restaurant.name,restaurant_path(@restaurant)
    add_breadcrumb 'Edit Restaurant',new_restaurant_path(@restaurant)
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params[:restaurant])
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Deleted a Restaurant successfully.'
  end

  private
    def init_breadcrumb
      add_breadcrumb 'All Restaurants', restaurants_path
    end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/consumer/restaurants_helper.rb
module Consumer::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/consumer/restaurants/_sidebar.html.haml
.sidenav
  .search-box
    = form_tag '',class:'search',method: :get do
      = text_field_tag :search, 'Search'
  = link_to 'Overview', overview_consumer_restaurant_path(@restaurant), class:'nav-link border-top'
  = link_to 'Restaurant', restaurant_consumer_restaurant_path(@restaurant), class:'nav-link'
  = link_to 'Service', service_consumer_restaurant_path(@restaurant), class:'nav-link'
  = link_to 'Dishes', dishes_consumer_restaurant_path,class:'nav-link'

app/views/consumer/restaurants/_subheading.html.haml
.page-header.page-header-with-buttons
  %h1.pull-left
    %i.icon-dashboard
    %span.category-name{data: @category}=heading
  #date_range.col-md-3
    .input-group
      %input.form-control.daterange{:placeholder => "Select daterange", :type => "text", name: 'daterange'}
        %span#daterange2.input-group-addon
          %i.icon-calendar

:javascript
  // Reset the dates from cookie
  $('input[name="daterang"]').resetDateCookie();

  $('input[name="daterange"]').daterangepicker(
  {
    format: 'YYYY-MM-DD',
    startDate: #{Date.today.strftime},
    endDate: #{Date.today.next_month.strftime}
  },
   function(start, end) {
     start = start.format('YYYY-MM-DD')
     end = end.format('YYYY-MM-DD')
     $(this).setDateCookie(start,end);
     drawChart();
   }
  );

- if false
  %span.date-range
  = form_tag '', method: :get do
    = date_select("date" , "start_date", {:default => @start_date, :order => [:month, :day, :year], :use_short_month => true, :end_year => Date.today.year}, {:class => "input-mini"})
    to
    = date_select("date" , "end_date", {:default => @end_date, :order => [:month, :day, :year], :use_short_month => true, :end_year => Date.today.year}, {:class => "input-mini"})
    = submit_tag  'Draw',class: 'submit btn btn-small btn-info'

app/views/consumer/restaurants/dishes.html.haml
:javascript
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);

  function drawChart() {

       response = $.ajax({
                         url: "#{"/consumer/restaurants/#{@restaurant.id}/dish_chart"} ",
                         dataType:"json",
                         async: false
                         }).responseText;

      jsonData = $.parseJSON(response);
      columns = jsonData['columns'];
      rows = jsonData['rows'];

      var data = new google.visualization.DataTable();
      data.addColumn('date', 'Date');

      for (var i = 0; i < columns.length; i++) {
         data.addColumn('number',columns[i] ,{role: 'annotation'}  );
      }
      for(var i=0; i< rows.length; i++){
        rows[i][0] = new Date(rows[i][0]*1000);
      }
      data.addRows(rows);

      var options = {
          pointSize: 5,
          vAxis: {format:'#',
                    viewWindow:{
                      max:5,
                      min:0
                    }
                  }
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
      chart.draw(data, options);
  }


.row-fluid
  .sidebar
    = render :partial => 'sidebar'
#container
  .span10.analytics
    = render :partial => 'subheading', :locals => {:heading => 'Dishes'}

  .row-fluid
    .span6
      %table{:id=>'dishes_list',:class=>'table-hover table table-bordered'}
        %tr
          %th
            Name
          %th
            Rating
          %th
            No. of Ratings
        - @dishes.each do |k,v|
          %tr{:id =>k,:class=>'dish-row'}
            %td
              = k.upcase
            %td
              =v[1]
            %td
              = v[0]
  .row-fluid
    %h3.dish-title

  #chart_div.span8

app/views/consumer/restaurants/orig_overview.html.haml
:javascript
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);

  function drawChart() {
      //var data = google.visualization.arrayToDataTable(#{raw @count_array.to_json});
      var data = new google.visualization.DataTable();

      data.addColumn('date', 'Date');
      data.addColumn('number', '# of reviews',{role: 'annotation'}  );

       js_data =#{@count_array.to_json};

      for(var i=0; i< js_data.length; i++){
        js_data[i][0] = new Date(js_data[i][0]*1000);
      }
        console.log(js_data);
      data.addRows(js_data);

      var options = {
          pointSize: 5,
          vAxis: {format:'#',
                    viewWindow:{
                      max:10,
                      min:0
                    }
                  }
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
      chart.draw(data, options);
  }

.row-fluid
  .span3.sidebar
    = render :partial => 'sidebar'

  .span9.analytics
    = render :partial => 'subheading', :locals => {:heading => 'Overview'}

    #reviews_score
    Restaurant
    = @reviews_score.category_score("restaurant")
    Service
    = @reviews_score.category_score("service")
    Dishes
    = @reviews_score.dish_score
    Food
    = @reviews_score.category_score("food")

    %h4 Reviews
    #chart_div

app/views/consumer/restaurants/overview.html.haml
:javascript
  // Resetting the chart parameters
  $.cookie('chart_parameters','')

#consumer_overview
  .col-xs-12
    = render :partial => 'subheading', :locals => {:heading => 'Overview'}
    .row.box
      .col-xs-6.col-md-2
        .box-content.box-statistic.green-background
          %h3.title.text-success
            = (score = @reviews_score.category_score("restaurant")) ? score.round(1) : "N/A"
          %small Restaurant
          .text-success.icon-flag.align-right
      .col-xs-6.col-md-2
        .box-content.box-statistic
          %h3.title.text-info
            = (score = @reviews_score.category_score("service")) ? score.round(1) : "N/A"
          %small Service
          .text-info.icon-refresh.align-right
      .col-xs-6.col-md-2
        .box-content.box-statistic
          %h3.title.text-info
            = (score = @reviews_score.dish_score) ? score.round(1) : "N/A"
          %small Dishes
          .text-info.icon-time.align-right
      .col-xs-6.col-md-2
        .box-content.box-statistic
          %h3.title.text-info
            = (score = @reviews_score.category_score("food")) ? score.round(1) : "N/A"
          %small Food
          .text-info.icon-time.align-right

    :javascript
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);

      function drawChart() {
          //var data = google.visualization.arrayToDataTable(#{raw @count_array.to_json});
          var data = new google.visualization.DataTable();

          data.addColumn('date', 'Date');
          data.addColumn('number', '# of reviews',{role: 'annotation'}  );

           js_data =#{@count_array.to_json};

          for(var i=0; i< js_data.length; i++){
            js_data[i][0] = new Date(js_data[i][0]*1000);
          }
            console.log(js_data);
          data.addRows(js_data);

          var options = {
              pointSize: 5,
              vAxis: {format:'#',
                        viewWindow:{
                          max:10,
                          min:0
                        }
                      }
          };

          var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
          chart.draw(data, options);
      }

    .col-xs-12
      %h4 Reviews
      .box#chart_div

      %h4 Frequently Rated Dishes
      .row.box
        - @trending_dishes.each do |k,v|
          .col-xs-6.col-md-2
            .box-content.box-statistic
              %h3.title.text-success= v[1]
              %small #{ k.humanize} (#{v[0]})
              .text-success.icon-arrow-up.align-right.percent
                31%

app/views/consumer/restaurants/restaurant.html.haml
:javascript
  // Resetting the chart parameters
  $.cookie('chart_parameters','')
#consumer_restaurant
  .col-xs-12
    = render :partial => 'subheading', :locals => {:heading => @category.capitalize}
    .row.box
      .col-xs-6.col-md-3
        .box-content.box-statistic.green-background
          %h3.title.text-success= @reviews_score.category_score(@category).round(1)
          %small=@category.capitalize
          .text-success.icon-flag.align-right
      - @reviews_score.category_features_scores(@category).each do |k,v|
        .col-xs-6.col-md-3
          .box-content.box-statistic
            %h3.title.text-info=v.round(1)
            %small= k.humanize
            .text-info.icon-glass.align-right
  .row
    .col-xs-12
      %h2.pull-left{:data=>{'category'=>@category}}
        %i.icon-bar-chart.subheader
        %span
          = @category.capitalize
          Trend
  .col-xs-12
    .row
      #chart_parameters
        %center
          .form-group.box
            - @reviews_score.category_features_scores(@category).each do |k,v|
              %label.checkbox-inline
                = check_box_tag(k,value = "1", checked = false,options = {class: "chart-params"})
                = k.humanize
      #chart_div

  :javascript
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);

    function drawChart() {

         response = $.ajax({
                           url: "#{"/consumer/restaurants/#{@restaurant.id}/features"} ",
                           dataType:"json",
                           async: false
                           }).responseText;

        jsonData = $.parseJSON(response);
        columns = jsonData['columns'];
        rows = jsonData['rows'];

        var data = new google.visualization.DataTable();
        data.addColumn('date', 'Date');

        for (var i = 0; i < columns.length; i++) {
           data.addColumn('number',columns[i] ,{role: 'annotation'}  );
        }
        for(var i=0; i< rows.length; i++){
          rows[i][0] = new Date(rows[i][0]*1000);
        }
        data.addRows(rows);

        var options = {
            pointSize: 5,
            vAxis: {format:'#',
                      viewWindow:{
                        max:5,
                        min:0
                      }
                    }
        };

        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }

  

app/views/consumer/restaurants/show.html.haml
:javascript
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);

  function drawChart() {
      //var data = google.visualization.arrayToDataTable(#{raw @count_array.to_json});
      var data = new google.visualization.DataTable();

      data.addColumn('date', 'Date');
      data.addColumn('number', '# of reviews',{role: 'annotation'}  );

       js_data =#{@count_array.to_json};

      for(var i=0; i< js_data.length; i++){
        js_data[i][0] = new Date(js_data[i][0]*1000);
      }
        console.log(js_data);
      data.addRows(js_data);

      var options = {
          title: 'Reviews',
          pointSize: 5,
          vAxis: {format:'#',
                    viewWindow:{
                      max:10,
                      min:0
                    }
                  }
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
      chart.draw(data, options);
  }

.row-fluid
  .span2.sidebar
    .container
      %ul.nav.nav-list
        %li
          = link_to 'Reviews', [:review_chart,:consumer,@restaurant]
        %li
          = link_to 'Service', [:review_chart,:consumer,@restaurant]
        %li
          = link_to 'Dishes', [:review_chart,:consumer,@restaurant]

  .span7
    #chart_div
  .span3
    = form_tag [:review_chart,:consumer,@restaurant], method: :get,class:'date' do
      = label_tag :start_date
      = date_select("date" , "start_date", :start_year => 2010, :end_year => 2012, :order => [:month, :day, :year], :use_short_month => true, :html=>{:class => "input-mini"} )
      = label_tag :end_date
      = date_select("date" , "end_date", :start_year => 2010, :end_year => 2015, :order => [:month, :day, :year], :use_short_month => true,:html=>{:class => "input-mini"} )
      %br
      = submit_tag  'Draw',class: 'btn btn-small btn-info'