config/routes.rb
Tomato::Application.routes.draw do
  
  devise_for :users
  get "user/feedbacks"

  namespace :admin do
    resources :restaurants do
      resources :reviews do
        resources :notes ,only: [:destroy]
        collection do
          get 'zomato'
          get 'burrp'
          get 'yelp'
          get 'foursquare'
        end
      end
    end
  end


  namespace :consumer do
    resources :restaurants, only: [] do
      member do
        get :overview
        post :overview
        get :restaurant
        get :features
        get :service
        get :dishes
        get :dish_chart
      end
    end
  end

  resources :restaurants do 
    resources :reviews do 
      member do
        get 'give_feedback'
      end
      collection do
        get 'zomato'
        get 'burrp'
        get 'yelp'
        get 'foursquare'
      end
    end
  end

  resources :feedbacks do
    resources :notes ,only: [:create,:destroy]
    resource :parameter, :only => :update
  end

  root :to => 'home#index'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :address, :name, :phone, :zomato_url, :burrp_url, :yelp_url, :foursquare_url
  has_many :reviews, :order => "id DESC"

  def collected_notes
    @collected_notes ||= reviews.collect(&:consolidated_notes)
  end

  def uniq_items
    collected_notes.collect(&:keys).flatten
  end

  def uniq_items_dist
    uniq_items.inject(Hash.new(0)) { |total, e| total[e] += 1 ;total}
  end

  def date_ordered_reviews
    reviews.order("review_created_at").group_by {|r| r.review_created_at.to_date}.to_a
  end

=begin
  def clusters
    @clusters ||= Util.cluster uniq_items_dist.keys
  end

  def cluster_label cluster
    label = cluster.first
    label_score = uniq_items_dist[label]
    cluster.each do |string|
      if uniq_items_dist[string] > label_score
        label = string 
        label_score = uniq_items_dist[string]
      end
    end
    label
  end

  def cluster_metrics cluster
    cluster_metrics = []

    date_ordered_reviews.each do |date ,reviews|
      puts date

      total_score = 0
      total_mentions = 0

      reviews.each do |review|
        notes = review.consolidated_notes
        cluster.each do |item|
          if notes[item]
            total_score += notes[item]
            total_mentions += 1
          end
        end
      end

      cluster_metrics << [date, {:total_score => total_score, :total_mentions => total_mentions}]

    end
    
    cluster_metrics.select {|e| e.second[:total_mentions] > 0}.map {|e| [e.first.to_time.to_i*1000, e.second[:total_score]/e.second[:total_mentions]] }
  end
=end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_filter :set_admin
  before_filter :authenticate_user!
  before_filter :authenticate_admin!
  before_filter :init_breadcrumb

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
    @review = Review.new
    render 'restaurants/index'
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    add_breadcrumb @restaurant.name,admin_restaurant_path(@restaurant)
    @reviews = @restaurant.reviews
    @review = Review.new(restaurant_id: @restaurant.id)
    #compute_cluster_metrics

    render 'restaurants/show'
  end

  def new
    @restaurant = Restaurant.new
    add_breadcrumb 'New Restaurant',new_admin_restaurant_path

    render 'restaurants/new'
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    add_breadcrumb @restaurant.name,admin_restaurant_path(@restaurant)
    add_breadcrumb 'Edit Restaurant',edit_admin_restaurant_path(@restaurant)
    render 'restaurants/edit'
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    if @restaurant.save
      redirect_to admin_restaurant_path(@restaurant), notice: 'Restaurant was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params[:restaurant])
      redirect_to request.referer, notice: 'Restaurant was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to request.referer, notice: 'Deleted a Restaurant successfully.'
  end

  private
    def authenticate_admin!
      redirect_to root_path, alert: "Admin area restricted !"  unless admin?
    end

    def admin?
      current_user.has_role? :admin
    end

    def init_breadcrumb
      add_breadcrumb 'Admin', admin_restaurants_path
      add_breadcrumb 'All Restaurants', admin_restaurants_path
    end

    def compute_cluster_metrics
      @clusters = @restaurant.clusters
    end

end

app/controllers/consumer/restaurants_controller.rb
class Consumer::RestaurantsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_restaurant
  before_filter :load_reviews
  before_filter :load_dish, only: [:dish_chart]

  layout 'consumer'

  def overview
    review_hash=@reviews.group("date(review_created_at)").count()
    @count_array = review_hash.to_a
    @count_array.sort! { |a, b| a.first <=> b.first }.collect! { |e| [e.first.to_time.to_i, e.second] }
    ob = Tools::ReviewsScore.new(@reviews)
    @trending_dishes = ob.trending_dishes
  end

  def category_chart

  end

  def restaurant
    ob = Tools::ReviewsScore.new(@reviews)
    @category = 'restaurant'
  end

  def features
    ob = Tools::ReviewsScore.new(@reviews)
    category = cookies['category']
    category_rating_hash = ob.category_rating_hashes([category])
    feature_rating_hashes_orig = ob.feature_rating_hashes(chart_parameters) if chart_parameters
    feature_rating_hashes_orig ? (rating_hashes_orig = category_rating_hash.merge feature_rating_hashes_orig) : rating_hashes_orig = category_rating_hash
    #Get date points from all features for use as keys
    keys = []
    rating_hashes_orig.values.each{|hash| keys.push hash.keys  }        #.inject {|union,hash| hash.keys | union.keys}
    keys.flatten!().uniq!
    if keys
      @rating_hash = {}
      (keys).each {|key,value| @rating_hash[key]=  rating_hashes_orig.values.collect{|hash| hash[key] } }
      #(keys).each {|key| @feature_rating_hash[key]= @parking_rating_hash[key],@ambience_rating_hash[key]}
      @rating = @rating_hash.to_a.collect{|r|  r[1].unshift(r[0].to_time.to_i)}
      @rating.sort! { |a, b| a.first <=> b.first }
      render json: {'columns'=>chart_parameters.push(category).collect(&:humanize),'rows'=> @rating}
    end
  end

  def service
    ob = Tools::ReviewsScore.new(@reviews)
    @category = 'service'
    render 'restaurant'
  end



  def dishes
    ob = Tools::ReviewsScore.new(@reviews)
    @dishes = ob.all_dishes
    cookies['dish']='South'
  end

  #Endpoint for returning chart data for a specific dish
  def dish_chart
    ob = Tools::ReviewsScore.new(@reviews)
    rating_hash = ob.time_vs_dish_rating @dish
    @rating = rating_hash.to_a.collect{|r|  [r[0].to_time.to_i,r[1]]}
    render json: {'columns'=>[@dish],'rows'=>@rating}
  end



  private
  def load_reviews
    load_restaurant
    load_start_and_end_dates

    @reviews = @restaurant.reviews.where(:review_created_at => (@start_date..@end_date))
    @reviews_score = Tools::ReviewsScore.new(@reviews)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def load_start_and_end_dates
    # Cookies were set on the browser.
    if (cookies['start_day'].present?)
      @start_date = Date.new cookies['start_year'].to_i, cookies['start_month'].to_i, cookies['start_day'].to_i
      @end_date = Date.new cookies['end_year'].to_i, cookies['end_month'].to_i, cookies['end_day'].to_i
    else
      @start_date = Date.today - 1000.days
      @end_date = Date.today
    end
  end

  def chart_parameters
  #TODO Memoize this shit
    if cookies['chart_parameters']
      @chart_parameters = cookies['chart_parameters'].split(',')
    else
      []
    end
  end

  def load_dish
    @dish = cookies['dish']
  end



end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :init_breadcrumb

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
    @review = Review.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    add_breadcrumb @restaurant.name,restaurant_path(@restaurant)
    @reviews = @restaurant.reviews
    @review = Review.new(restaurant_id: @restaurant.id)
  end

  def new
    @restaurant = Restaurant.new
    add_breadcrumb 'New Restaurant',new_restaurant_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    add_breadcrumb @restaurant.name,restaurant_path(@restaurant)
    add_breadcrumb 'Edit Restaurant',new_restaurant_path(@restaurant)
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params[:restaurant])
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Deleted a Restaurant successfully.'
  end

  private
    def init_breadcrumb
      add_breadcrumb 'All Restaurants', restaurants_path
    end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/consumer/restaurants_helper.rb
module Consumer::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.haml
#new_restaurant_form
  = form_for (@admin ? [:admin, @restaurant] : [@restaurant]),html: { class: 'form-horizontal'} do |f|
    -if @restaurant.errors.any?
      %div#error_explanation
        %h2
          = pluralize(@restaurant.errors.count, "error")
          prohibited this restaurant from being saved
        %ul
          -@restaurant.errors.full_messages.each do |msg|
            %li
              = msg
    .form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-md-8= f.text_field :name, class: 'form-control'
    .form-group
      = f.label :address, class: 'col-sm-2 control-label'
      .col-md-8= f.text_area :address, class: 'form-control'
    .form-group
      = f.label :phone, class: 'col-sm-2 control-label'
      .col-md-8= f.text_field :phone, class: 'form-control'
    .form-group
      = f.label :zomato_url,class: 'col-sm-2 control-label'
      .col-md-8= f.text_field :zomato_url, class: 'form-control'
    .form-group
      = f.label :burrp_url, class: 'col-sm-2 control-label'
      .col-md-8= f.text_field :burrp_url, class: 'form-control'
    .form-group
      = f.label :yelp_url, class: 'col-sm-2 control-label'
      .col-md-8= f.text_field :yelp_url, class: 'form-control'
    .form-group
      = f.label ' ',class: 'col-sm-2 control-label'
      .col-md-8= f.submit :Save, class: 'btn btn-default'

app/views/restaurants/edit.html.haml
.row
  .col-xs-12.container-center
    %h4
      Editing restaurant

    = render 'restaurants/form'
    = link_to '< Back', (@admin ? admin_restaurants_path : restaurants_path)
    |
    = link_to 'Show', (@admin ? admin_restaurant_path(@restaurant) : restaurant_path(@restaurant))

app/views/restaurants/index.html.haml
#restaurant.container-center
  .col-xs-12
    %h4.heading
      Restaurants
      %i.glyphicon.glyphicon-glass
    %table.table-striped.table-bordered
      %tr
        %th Name
        %th Address
        %th Phone
        %th{colspan:'3'} Actions
      -@restaurants.each do |restaurant|
        %tr
          %td= link_to restaurant.name,(@admin ? admin_restaurant_path(restaurant) : restaurant_path(restaurant))
          %td= restaurant.address
          %td= restaurant.phone
          %td.show-action
            = link_to (@admin ? admin_restaurant_path(restaurant) : restaurant_path(restaurant)) do
              %i.glyphicon.glyphicon-new-window
              Show
          %td.edit-action
            = link_to (@admin ? edit_admin_restaurant_path(restaurant) : edit_restaurant_path(restaurant)) do
              %i.glyphicon.glyphicon-pencil
              Edit
          %td.delete-action
            = link_to (@admin ? admin_restaurant_path(restaurant) : restaurant_path(restaurant)), method: :delete, data: { confirm: 'Are you sure?' } do
              %i.glyphicon.glyphicon-trash
              Destroy
  .col-xs-12
    = link_to (@admin ? new_admin_restaurant_path : new_restaurant_path), class: 'new-restaurant btn btn-default' do
      %i.glyphicon.glyphicon-plus-sign
      New Restaurant
    .paginate
      = paginate @restaurants

app/views/restaurants/new.html.haml
.row-fluid
  .span10.offset1
    %h4
      New restaurant
    = render 'restaurants/form'
    = link_to '< Back to Restaurants list', (@admin ? admin_restaurants_path : restaurants_path)

app/views/restaurants/show.html.haml
#restaurant.container-center
  .col-xs-8
    %h3= @restaurant.name
    .right
      = link_to (@admin ? edit_admin_restaurant_path(@restaurant) : edit_restaurant_path(@restaurant)) do
        %i.glyphicon.glyphicon-pencil
        Edit Details

    .block= @restaurant.address
    .block= @restaurant.phone


    -if @restaurant.zomato_url
      .clearfix
        = link_to 'Zomato Reviews',(@admin ? zomato_admin_restaurant_reviews_path(@restaurant) : zomato_restaurant_reviews_path(@restaurant)),class: "btn btn-default tiny block"
    -if @restaurant.burrp_url
      .clearfix
        = link_to 'Burrp Reviews',(@admin ? burrp_admin_restaurant_reviews_path(@restaurant) : burrp_restaurant_reviews_path(@restaurant)),class: "btn btn-default tiny block"
    -if @restaurant.yelp_url
      .clearfix
        = link_to 'Yelp Reviews',(@admin ? yelp_admin_restaurant_reviews_path(@restaurant) : yelp_restaurant_reviews_path(@restaurant)),class: "btn btn-default tiny block"
    -#-if @restaurant.foursquare_url
      .clearfix
        = link_to "Foursquare Reviews",(@admin ? foursquare_admin_restaurant_reviews_path(@restaurant) : foursquare_restaurant_reviews_path(@restaurant)), class: "btn tiny block"
  .col-xs-4#new_review
    %h4
      %i.glyphicon.glyphicon-puls-sign
      New Review
    = render 'reviews/form'
.row.container-center
  - if false
    .row.col-md-6.col-xs-12.col-md-offset-1
      %h4 Cluster Metrics
      - @clusters.each_with_index do |cluster, index|
        %h6
          = @restaurant.cluster_label(cluster)
          = "( #{cluster.join(', ')} )"
        .cluster-chart{:id => "cluster_#{index}"}
          :javascript
            $.plot(
              $("#cluster_#{index}"),
              [ { data: #{@restaurant.cluster_metrics(cluster)}}],
              {
                series: {
                   lines: { show: true },
                   points: { show: true }
                },

                grid: { hoverable: true, clickable: true },
                xaxis: { mode: "time", minTickSize: [1, "day"],timeformat: "%m/%d/%y"},
                yaxis: { min: 1, max: 5},
                colors: ["#F90", "#222", "#666", "#BBB"]
              }
            );