config/routes.rb
Tomato::Application.routes.draw do
  
  devise_for :users
  get "user/feedbacks"

  namespace :admin do
    resources :restaurants do
      resources :reviews do
        resources :notes ,only: [:destroy]
        collection do
          get 'zomato'
          get 'burrp'
          get 'yelp'
          get 'foursquare'
        end
      end
    end
  end


  namespace :consumer do
    resources :restaurants, only: [] do
      member do
        get :overview
        post :overview
        get :restaurant
        get :features
        get :service
        get :dishes
        get :dish_chart
      end
    end
  end

  resources :restaurants do 
    resources :reviews do 
      member do
        get 'give_feedback'
      end
      collection do
        get 'zomato'
        get 'burrp'
        get 'yelp'
        get 'foursquare'
      end
    end
  end

  resources :feedbacks do
    resources :notes ,only: [:create,:destroy]
    resource :parameter, :only => :update
  end

  root :to => 'home#index'
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 
      Tomato
    = stylesheet_link_tag "data", :media => "all" 
    = javascript_include_tag "data"
    = csrf_meta_tags
%body

.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} Tomato
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'Restaurants',restaurants_path
        %li.dropdown
          %a{ href: '#',class:"dropdown-toggle", "data-toggle"=>"dropdown"}
            Admin
            %b.caret
            %ul.dropdown-menu
              %li= link_to 'Restaurants', admin_restaurants_path
      %ul.nav.navbar-nav.pull-right
        - if user_signed_in?
          %li= link_to 'User Feedback',user_feedbacks_path
        %li.dropdown
          %a{ href: '#',class:"dropdown-toggle", "data-toggle"=>"dropdown"}
            - if user_signed_in?
              %i.glyphicon.glyphicon-user
              = current_user.email
              %b.caret
              %ul.dropdown-menu
                %li= link_to 'Edit Account', edit_user_registration_path
                %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
            -else
              %li= link_to 'Sign In',new_user_session_path

.col-xs-12
  .container-center.row
    = render 'layouts/messages'
  - if @breadcrumbs.present?
    .breadcrumb
      - @breadcrumbs[0..-2].each do |txt, path|
        = link_to(txt, path)
        %span{:class => "divider"}
        &raquo;
      = @breadcrumbs.last.first
  = yield

.footer.span10.offset1
  %center
    %hr
    Tomato &copy;
    = Time.now.year

app/views/layouts/consumer.html.haml
!!!
%html
  %head
    %title
      Tomato
    = stylesheet_link_tag "consumer", :media => "all"
    = javascript_include_tag "consumer"
    = stylesheet_link_tag 'http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css'
    %script{:src => "https://www.google.com/jsapi", :type => "text/javascript"}

    = csrf_meta_tags
%body.contrast-red
  - if false
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          .brand= @restaurant.name

  %header
    %nav.navbar.navbar-default
      %a.navbar-brand{:href => "index.html"}
        %img.logo{:alt => "Flatty", :height => "21", :src => image_path("flatty/logo.svg"), :width => "81"}/
        %img.logo-xs{:alt => "Flatty", :height => "21", :src => image_path("flatty/logo_xs.svg"), :width => "21"}/
      %a.toggle-nav.btn.pull-left{:href => "#"}
        %i.icon-reorder
      %ul.nav
        %li.dropdown.dark.user-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %img{:alt => "Mila Kunis", :height => "23", :src => image_path("flatty/avatar.jpg"), :width => "23"}/
            %span.user-name Mila Kunis
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "user_profile.html"}
                %i.icon-user
                Profile
            %li
              %a{:href => "user_profile.html"}
                %i.icon-cog
                Settings
            %li.divider
            %li
              %a{:href => "sign_in.html"}
                %i.icon-signout
                Sign out
      %form.navbar-form.navbar-right.hidden-xs{:action => "search_results.html", :method => "get"}
        %button.btn.btn-link.icon-search{:name => "button", :type => "submit"}
        .form-group
          %input#q_header.form-control{:autocomplete => "off", :name => "q", :placeholder => "Search...", :type => "text", :value => ""}/

  #wrapper
    #main-nav-bg
    %nav#main-nav
      .navigation
        %ul.nav.nav-stacked
          %li{:class => (action_name == 'overview' ? 'active' : nil)}
            = link_to [:overview, :consumer, @restaurant] do
              %i.icon-dashboard
              %span Overview
          %li{:class => (action_name == 'restaurant' ? 'active' : nil)}
            = link_to [:restaurant, :consumer, @restaurant] do
              %i.icon-star
              %span Restaurant
          %li{:class => (action_name == 'service' ? 'active' : nil)}
            = link_to [:service, :consumer, @restaurant] do
              %i.icon-table
              %span Service

    %section#content
      .container
        #content-wrapper.row
          = yield

        %footer#footer
          .footer-wrapper
            .row
              %center
                Tomato &copy;
                = Time.now.year
              

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title Foodlytics | Understand customers like never before
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,300,700,500,900", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}/
    = stylesheet_link_tag "home", media: 'all'
    = javascript_include_tag "home"
    = favicon_link_tag 'favicon.ico'
  %body
    #home.header
      .header_top
        .wrap
          .logo
            = link_to root_path do
              .logo-img= image_tag "logo.png"
          .menu
            %ul
              %li
                %a.scroll{:href => "#home"} Home
              %li
                %a.scroll{:href => "#features"} Features
              %li
                %a.scroll{:href => "#tour"} Tour
              %li
                %a.scroll{:href => "#pricing_dashboard"} Pricing
              %li.login
                #loginContainer
                  = link_to 'Login',new_user_session_path,id: '#loginButton'
    .main
      .content
        = yield
    .copy_right
      .wrap
        %p
          %i.fa.fa-heart
          = link_to 'Foodlytics',"#"
          &copy;
          = Time.now.year

app/views/layouts/restaurant_owner.html.haml
!!!
%html
  %head
    %title
      Tomato
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = stylesheet_link_tag 'http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css'
    %script{:src => "https://www.google.com/jsapi", :type => "text/javascript"}

    = csrf_meta_tags
%body.contrast-red
  - if false
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          .brand= @restaurant.name

  %header
    %nav.navbar.navbar-default
      %a.navbar-brand{:href => "index.html"}
        %img.logo{:alt => "Flatty", :height => "21", :src => image_path("flatty/logo.svg"), :width => "81"}/
        %img.logo-xs{:alt => "Flatty", :height => "21", :src => image_path("flatty/logo_xs.svg"), :width => "21"}/
      %a.toggle-nav.btn.pull-left{:href => "#"}
        %i.icon-reorder
      %ul.nav
        %li.dropdown.dark.user-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %img{:alt => "Mila Kunis", :height => "23", :src => image_path("flatty/avatar.jpg"), :width => "23"}/
            %span.user-name Mila Kunis
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "user_profile.html"}
                %i.icon-user
                Profile
            %li
              %a{:href => "user_profile.html"}
                %i.icon-cog
                Settings
            %li.divider
            %li
              %a{:href => "sign_in.html"}
                %i.icon-signout
                Sign out
      %form.navbar-form.navbar-right.hidden-xs{:action => "search_results.html", :method => "get"}
        %button.btn.btn-link.icon-search{:name => "button", :type => "submit"}
        .form-group
          %input#q_header.form-control{:autocomplete => "off", :name => "q", :placeholder => "Search...", :type => "text", :value => ""}/

  #wrapper
    #main-nav-bg
    %nav#main-nav
      .navigation
        %ul.nav.nav-stacked
          %li{:class => (action_name == 'overview' ? 'active' : nil)}
            = link_to [:overview, :consumer, @restaurant] do
              %i.icon-dashboard
              %span Overview
          %li{:class => (action_name == 'restaurant' ? 'active' : nil)}
            = link_to [:restaurant, :consumer, @restaurant] do
              %i.icon-star
              %span Restaurant
          %li{:class => (action_name == 'service' ? 'active' : nil)}
            = link_to [:service, :consumer, @restaurant] do
              %i.icon-table
              %span Service

    %section#content
      .container
        #content-wrapper.row
          = yield

        %footer#footer
          .footer-wrapper
            .row
              %center
                Tomato &copy;
                = Time.now.year
              